// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCS.App.Persistencia;

namespace UCS.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210916145218_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UCS.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("estadocovid")
                        .HasColumnType("int");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("UCS.App.Dominio.Salones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cantidadActualPersonas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maximoAforo")
                        .HasColumnType("int");

                    b.Property<int>("numeroSalon")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Salones");
                });

            modelBuilder.Entity("UCS.App.Dominio.Sedes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("nombreFacultad")
                        .HasColumnType("int");

                    b.Property<int>("salonesDisponibles")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("UCS.App.Dominio.SistemaIngresoPersonal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("autoriza")
                        .HasColumnType("bit");

                    b.Property<DateTime>("horayFechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("horayFechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("pruebacovid")
                        .HasColumnType("bit");

                    b.Property<string>("sede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sintomas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SitemaIngresoPersonal");
                });

            modelBuilder.Entity("UCS.App.Dominio.Universidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Universidades");
                });

            modelBuilder.Entity("UCS.App.Dominio.Directivo", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<string>("unidadDesempeña")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Directivo");
                });

            modelBuilder.Entity("UCS.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<string>("Semestre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carrera")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("UCS.App.Dominio.PersonalAseo", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<DateTime>("turnoServicio")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("PersonalAseo");
                });

            modelBuilder.Entity("UCS.App.Dominio.Profesores", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materia")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Profesores");
                });
#pragma warning restore 612, 618
        }
    }
}
