// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCS.App.Persistencia;

namespace UCS.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211012213612_relacionesAgregadas")]
    partial class relacionesAgregadas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UCS.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoCovid")
                        .HasColumnType("int");

                    b.Property<int?>("SistemaIngresoPersonalid")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sintomas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SistemaIngresoPersonalid");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("UCS.App.Dominio.Salon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("SistemaIngresoPersonalid")
                        .HasColumnType("int");

                    b.Property<int>("maximoAforo")
                        .HasColumnType("int");

                    b.Property<int>("numeroDePuesto")
                        .HasColumnType("int");

                    b.Property<int>("numeroSalon")
                        .HasColumnType("int");

                    b.Property<int?>("profesorid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SistemaIngresoPersonalid");

                    b.HasIndex("profesorid");

                    b.ToTable("Salon");
                });

            modelBuilder.Entity("UCS.App.Dominio.Sede", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("SistemaIngresoPersonalid")
                        .HasColumnType("int");

                    b.Property<int>("nombreFacultad")
                        .HasColumnType("int");

                    b.Property<int>("salonesDisponibles")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SistemaIngresoPersonalid");

                    b.ToTable("Sede");
                });

            modelBuilder.Entity("UCS.App.Dominio.SistemaIngresoPersonal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("autoriza")
                        .HasColumnType("bit");

                    b.Property<DateTime>("horayFechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("horayFechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("pruebacovid")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("SistemaIngresoPersonal");
                });

            modelBuilder.Entity("UCS.App.Dominio.Universidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Universidades");
                });

            modelBuilder.Entity("UCS.App.Dominio.Directivo", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<string>("unidadDesempeña")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Directivo");
                });

            modelBuilder.Entity("UCS.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<int?>("Salonid")
                        .HasColumnType("int");

                    b.Property<string>("Semestre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carrera")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Salonid");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("UCS.App.Dominio.PersonalAseo", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<DateTime>("turnoServicio")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("PersonalAseo");
                });

            modelBuilder.Entity("UCS.App.Dominio.Profesores", b =>
                {
                    b.HasBaseType("UCS.App.Dominio.Persona");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Profesores");
                });

            modelBuilder.Entity("UCS.App.Dominio.Persona", b =>
                {
                    b.HasOne("UCS.App.Dominio.SistemaIngresoPersonal", null)
                        .WithMany("persona")
                        .HasForeignKey("SistemaIngresoPersonalid");
                });

            modelBuilder.Entity("UCS.App.Dominio.Salon", b =>
                {
                    b.HasOne("UCS.App.Dominio.SistemaIngresoPersonal", null)
                        .WithMany("salones")
                        .HasForeignKey("SistemaIngresoPersonalid");

                    b.HasOne("UCS.App.Dominio.Profesores", "profesor")
                        .WithMany()
                        .HasForeignKey("profesorid");

                    b.Navigation("profesor");
                });

            modelBuilder.Entity("UCS.App.Dominio.Sede", b =>
                {
                    b.HasOne("UCS.App.Dominio.SistemaIngresoPersonal", null)
                        .WithMany("sedes")
                        .HasForeignKey("SistemaIngresoPersonalid");
                });

            modelBuilder.Entity("UCS.App.Dominio.Estudiante", b =>
                {
                    b.HasOne("UCS.App.Dominio.Salon", null)
                        .WithMany("estudiantes")
                        .HasForeignKey("Salonid");
                });

            modelBuilder.Entity("UCS.App.Dominio.Salon", b =>
                {
                    b.Navigation("estudiantes");
                });

            modelBuilder.Entity("UCS.App.Dominio.SistemaIngresoPersonal", b =>
                {
                    b.Navigation("persona");

                    b.Navigation("salones");

                    b.Navigation("sedes");
                });
#pragma warning restore 612, 618
        }
    }
}
